In [1]:
import numpy as np
import time

print("=" * 50)
print("NUMPY DATA EXPLORER")
print("=" * 50)

NUMPY DATA EXPLORER


In [2]:
print("\n1. ARRAY CREATION")

array1 = np.array([10, 20, 30, 40, 50])
array2 = np.arange(1, 13)
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))
random_array = np.random.randint(1, 100, (3, 4))


1. ARRAY CREATION


In [4]:
print("Array1:")
print(array1)


Array1:
[10 20 30 40 50]


In [5]:

print("\nArray2:")
print(array2)




Array2:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
print("\nZeros:")
print(zeros)




Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
print("\nOnes:")
print(ones)



Ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:

print("\nRandom Array:")
print(random_array)


Random Array:
[[25 91 31 17]
 [47 77 17 58]
 [32 60 97 92]]


In [9]:
# Indexing & Slicing
# -----------------------------
print("\n2. INDEXING & SLICING")

print("First Element:", array1[0])
print("Last Element:", array1[-1])
print("Slice:", array1[1:4])


2. INDEXING & SLICING
First Element: 10
Last Element: 50
Slice: [20 30 40]


In [10]:
# Reshape
# -----------------------------
print("\n3. RESHAPING")

reshaped = array2.reshape(3, 4)

print(reshaped)


3. RESHAPING
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
print("\n4. MATHEMATICAL OPERATIONS")

print("Addition")
print(array1 + 5)

print("Multiplication")
print(array1 * 2)

print("Square")
print(np.square(array1))


4. MATHEMATICAL OPERATIONS
Addition
[15 25 35 45 55]
Multiplication
[ 20  40  60  80 100]
Square
[ 100  400  900 1600 2500]


In [12]:
# Statistical Operations
# -----------------------------
print("\n5. STATISTICS")

print("Sum:", np.sum(array1))
print("Mean:", np.mean(array1))
print("Median:", np.median(array1))
print("Maximum:", np.max(array1))
print("Minimum:", np.min(array1))
print("Standard Deviation:", np.std(array1))


5. STATISTICS
Sum: 150
Mean: 30.0
Median: 30.0
Maximum: 50
Minimum: 10
Standard Deviation: 14.142135623730951


In [13]:
print("\n6. AXIS OPERATIONS")

print("Row Sum:")
print(np.sum(reshaped, axis=1))

print("Column Sum:")
print(np.sum(reshaped, axis=0))



6. AXIS OPERATIONS
Row Sum:
[10 26 42]
Column Sum:
[15 18 21 24]


In [14]:
print("\n7. BROADCASTING")

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

vector = np.array([10, 20, 30])

result = matrix + vector

print(result)


7. BROADCASTING
[[11 22 33]
 [14 25 36]]


In [15]:
# Save & Load
# -----------------------------
print("\n8. SAVE & LOAD")

np.save("saved_array.npy", reshaped)

loaded = np.load("saved_array.npy")

print("Loaded Array:")
print(loaded)



8. SAVE & LOAD
Loaded Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
print("\n9. PERFORMANCE TEST")

python_list = list(range(1000000))
numpy_array = np.arange(1000000)

start = time.time()
python_result = [x * 2 for x in python_list]
python_time = time.time() - start

start = time.time()
numpy_result = numpy_array * 2
numpy_time = time.time() - start

print(f"Python List Time : {python_time:.6f} sec")
print(f"NumPy Array Time : {numpy_time:.6f} sec")

if numpy_time < python_time:
    print("NumPy is Faster.")
else:
    print("Python List is Faster.")

print("\nProject Completed Successfully.")


9. PERFORMANCE TEST
Python List Time : 0.104318 sec
NumPy Array Time : 0.013125 sec
NumPy is Faster.

Project Completed Successfully.
